import PhoneInput from '../../rooms/components/PhoneInput';
import {phoneCountry} from '../../rooms/utils/phoneInput';
import {getCountryCallingCode,parsePhoneNumberFromString} from 'libphonenumber-js/max';
import React,{useState} from 'react';
import {editReservation,databaseError} from '../../../services/stayman';
import {money,nights} from '../../management/utils/metrics';
export default function EditReservation({reservation,guest,allocations,units,onSaved,onClose}) {
 const [snapshot]=useState(()=>({name:guest.full_name,phone:guest.phone,email:guest.email||'',arrival:reservation.check_in_date,departure:reservation.check_out_date,notes:reservation.notes,total:Number(reservation.total_amount)}));
 const [country,setCountry]=useState(()=>phoneCountry(guest.phone));
 const [values,setValues]=useState(()=>({...snapshot,phone:parsePhoneNumberFromString(snapshot.phone,phoneCountry(snapshot.phone))?.number||snapshot.phone})),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const parts=allocations.filter(a=>a.reservationDbId===reservation.id), unit=units.find(u=>u.id===parts[0]?.unitId);
 const datesChanged=values.arrival!==snapshot.arrival||values.departure!==snapshot.departure;
 const total=datesChanged?(unit?.nightlyRatePaise||0)*nights(values.arrival,values.departure):snapshot.total;
 const change=e=>setValues(v=>({...v,[e.target.name]:e.target.name==='phone'?e.target.value.replace(/[^+0-9() .-]/g,''):e.target.value}));
 async function submit(e){e.preventDefault();if(!parsePhoneNumberFromString(values.phone)?.isValid()){setError('Enter a valid phone number.');return;}if(!Number.isSafeInteger(total)||total<0){setError('Choose valid stay dates.');return;}setBusy(true);setError('');try{await editReservation(reservation.id,{...values,total},snapshot);await onSaved();onClose();}catch(e){setError(databaseError(e));}finally{setBusy(false);}}
 return <form onSubmit={submit} className="rounded-xl border p-4"><fieldset disabled={busy} className="space-y-4"><h2>Edit reservation</h2><label>Booking name<input name="name" required minLength={2} maxLength={100} value={values.name} onChange={change}/></label><PhoneInput required country={country} value={values.phone} onChange={phone=>setValues(v=>({...v,phone}))} onCountryChange={(c,n)=>{setCountry(c);setValues(v=>({...v,phone:'+'+getCountryCallingCode(c)+n}));}}/><label>Email<input name="email" type="email" maxLength={254} value={values.email} onChange={change}/></label><div className="grid grid-cols-2 gap-3"><label>Arrival<input name="arrival" type="date" required disabled={parts.length!==1||reservation.status==='CHECKED_IN'} value={values.arrival} onChange={change}/></label><label>Departure<input name="departure" type="date" required disabled={parts.length!==1} min={values.arrival} value={values.departure} onChange={change}/></label></div>{parts.length!==1&&<p className="muted">This booking has split bed assignments. Use Move bed / room to adjust assignments; date edits require a single assignment.</p>}<label>Notes<textarea name="notes" maxLength={1000} value={values.notes} onChange={change}/></label><div className="notice"><p>Booking total: {money(snapshot.total)} → <strong>{money(total)}</strong></p><p className="mt-1">{Number(reservation.paid_amount)>total?'Refund due: '+money(Number(reservation.paid_amount)-total):'Balance due: '+money(total-Number(reservation.paid_amount))}</p><p className="mt-2 text-xs">Changing dates uses the current nightly rate. Availability is checked on save. Recorded payments and submitted web check-ins are preserved.</p></div>{error&&<p role="alert" className="error">{error}</p>}<div className="flex justify-end gap-2"><button className="secondary" type="button" onClick={onClose}>Keep details</button><button className="primary">{busy?'Saving…':'Confirm changes'}</button></div></fieldset></form>;
}
